<a href="https://colab.research.google.com/github/annefrancine/Introduction-python/blob/master/Exercice_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Help
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

1) Creez et afficher un 3D-array

In [ ]:
a_3d = np.arange(24).reshape(4,3,2)
a_3d


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
a_3d[0][0]

array([0, 1])

In [ ]:
a_3d[2][0]

2) Créer une matrice échiquier (des 1 et des 0 alternés) de taille 8x8, de deux façons différentes

* en vous servant de slices

* en vous servant de la fonction tile

https://www.actionco.fr/Thematique/methodologie-1246/fiche-outils-10181/La-matrice-de-l-echiquier-326233.htm

In [ ]:
chess = np.zeros((8,8), dtype=int)
chess[::2,::2] = 1
chess[1::2,1::2] = 1
print(chess)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [ ]:
chess2 = np.tile([[1,0],[0,1]], (4,4))
print(chess2)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


3) Effectuer le calcul suivant : exp(cos2π+log(1.5))

In [ ]:
print(np.pi)

3.141592653589793


In [ ]:
np.exp(np.cos(2*np.pi)+(np.log (1.5)))

4.077422742688568

4) Créez et affichez un array a contenant les réels compris entre 5 et 50, avec un pas de 2.5.

In [ ]:
b = np.arange(5,50,2.5)
b

array([ 5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. , 27.5, 30. ,
       32.5, 35. , 37.5, 40. , 42.5, 45. , 47.5])

5) Créez un array X de taille  6×5  d'entiers aléatoires compris entre 1 et 100 ; Affichez X; Affichez la 3ème colonne de X;Affichez le dernier élément de X (dernière ligne, dernière colonne)

In [ ]:
np.random.seed(41)
x=np.random.randint(1,100,(6,5))
print(x)

[[65 36 13 99 81]
 [66 90 24 86 27]
 [57  4 36 51 71]
 [85 87 62 52 93]
 [89 76 93 53 56]
 [18 99 82 29 54]]


In [ ]:
print(x[:,2])

[13 24 36 62 93 82]


In [ ]:
print(x[-1,-1])

54


6)	Affichez tous les éléments pairs de la matrice X définie plus haut

In [ ]:
for element in x.flat:
  if(element % 2==0):
    print(element)

36
66
90
24
86
4
36
62
52
76
56
18
82
54


7) Effectuez le produit élément par élément, puis le produit matriciel des matrices :

In [ ]:
A=np.array ([[1,2],[0,1]])
B=np.array ([[3,2],[1,0]])
A

array([[1, 2],
       [0, 1]])

In [ ]:
B

array([[3, 2],
       [1, 0]])

In [ ]:
print(A*B)

[[3 4]
 [0 0]]


In [ ]:
np.dot(A,B)

array([[5, 2],
       [1, 0]])

8) Créez un array N de taille  100×10  contenant des nombres aléatoires suivant une loi Normale standard, grâce à la fonction np.random.randn(); Affichez la moyenne sur tout le tableau; Affichez l'écart-type des éléments de chaque colonne; Ces résultats valident-t-ils l'hypothèse de la loi utilisée?

In [ ]:
N = np.random.randn(100,10)
N

array([[-1.24328548e+00, -6.07749499e-01, -4.60213514e-01,
         4.36023595e-01, -8.22922475e-01,  4.60100357e-01,
         1.18994984e+00, -1.07829376e+00, -2.03890736e-02,
         5.46146349e-02],
       [-2.47215082e-01,  1.95220372e-02,  9.85186991e-02,
         1.26843416e+00, -9.37826317e-01, -5.43156155e-01,
         2.95860341e-01,  1.94505405e+00, -7.68954468e-01,
         1.66033979e+00],
       [ 2.58622956e+00, -4.99018947e-01,  2.15146581e-01,
        -4.51638398e-01,  7.81461692e-01, -1.70828735e+00,
        -4.13412445e-01, -4.66529661e-01,  3.10323970e-01,
        -2.05041886e-03],
       [ 2.96241712e-01, -3.48667532e-01,  1.46119763e-01,
        -1.44037819e+00,  3.94121366e-01,  4.01408699e-01,
        -2.82667973e-01, -8.70280082e-01, -2.43237132e+00,
         1.64070671e-01],
       [-1.40091151e+00,  8.55714077e-01, -1.72806123e+00,
         7.65962912e-01,  7.67648206e-01,  4.38011218e-02,
         3.22606304e-01, -3.80626405e-01,  1.10924255e+00,
         1.

In [ ]:
print(N.mean())

0.011115098263498246


In [ ]:
print(N.std( axis = 0))

[0.93546337 0.98460046 0.96772288 1.15218378 1.01851889 0.97392044
 1.03357358 0.95492264 1.02846522 1.01537225]


9) Résoudre le système d’équations 3x0 + x1 = 9 et x0 + 2x1 = 8

In [ ]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
x

array([2., 3.])

10) Créer la matrice ci-dessous à l'aide de fonctions génératives, de fonctions de manipulations et d'opérations simples

In [ ]:
mat = np.zeros(5)

In [ ]:
a = np.diag(np.ones(4),-1)
a

In [ ]:
b = np.diag(np.ones(3), -2)*2
b

In [ ]:
c = np.diag(np.ones(2), -3)*3
c

In [ ]:
d = np.diag(np.ones(1),-4)*4
d

In [ ]:
mat = mat+a+b+c+d

In [ ]:
mat = mat + np.transpose(mat)

In [ ]:
print(mat)

[[0. 1. 2. 3. 4.]
 [1. 0. 1. 2. 3.]
 [2. 1. 0. 1. 2.]
 [3. 2. 1. 0. 1.]
 [4. 3. 2. 1. 0.]]
